tap "dsully/tap"

# Shell
brew "zsh"
brew "powerlevel10k"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

# Essential CLI tools
brew "fd"
brew "fzf"
brew "bat"
brew "eza"
brew "tree"
brew "tmux"
brew "wget"
brew "curl"

brew "gh"
brew "dsully/tap/macos-defaults"
brew "mise"

# 1Password
cask "1password"
cask "1password-cli"

# Editor (pick one or both)
cask "cursor"
# cask "visual-studio-code"
cask "kitty"
cask "ghostty"


cask "google-chrome"
cask "raycast"