tap "dart-lang/dart"
tap "felangel/mason"
tap "fluttergen/tap"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "koekeishiya/formulae"
tap "leoafarias/fvm"
tap "shopify/shopify"
tap "stripe/stripe-cli"
# Run your GitHub Actions locally
brew "act"
# Image format providing lossless and lossy compression for web images
brew "webp"
# New file format for still image compression
brew "jpeg-xl"
# Codec library for encoding and decoding AV1 video streams
brew "aom"
# GitOps Continuous Delivery for Kubernetes
brew "argocd"
# Configuration editing tool and API
brew "augeas"
# Automatic configure script builder
brew "autoconf"
# Tool for generating GNU Standards-compliant Makefiles
brew "automake"
# C parser in Python
brew "pycparser"
# C Foreign Function Interface for Python
brew "cffi"
# Text processing system for reStructuredText
brew "docutils"
# Interpreted, interactive, object-oriented programming language
brew "python@3.11"
# Official Amazon AWS command-line interface
brew "awscli"
# User-friendly launcher for Bazel
brew "bazelisk"
# Core application library for C
brew "glib"
# GNU File, Shell, and Text utilities
brew "coreutils"
# International domain name library (IDNA2008, Punycode and TR46)
brew "libidn2"
# Library to load and enumerate PKCS#11 modules
brew "p11-kit"
# Validating, recursive, caching DNS resolver
brew "unbound"
# GNU Transport Layer Security (TLS) Library
brew "gnutls"
# Emacs dependency management
brew "cask"
# Cryptographic recipes and primitives for Python
brew "python-cryptography"
# Tool to obtain certs from Let's Encrypt and autoenable HTTPS
brew "certbot"
# Formatting tools for C, C++, Obj-C, Java, JavaScript, TypeScript
brew "clang-format"
# Cross-platform make
brew "cmake"
# Dependency manager for Cocoa projects
brew "cocoapods"
# Command-line tool for DigitalOcean
brew "doctl"
# Easiest way to build and release mobile apps
brew "fastlane"
# Firebase command-line tools
brew "firebase-cli"
# GitHub command-line tool
brew "gh"
# Library for JPEG-2000 image manipulation
brew "openjpeg"
# Interpreter for PostScript and PDF
brew "ghostscript"
# Distributed revision control system
brew "git"
# X.509 and CMS library
brew "libksba"
# GNU Pretty Good Privacy (PGP) package
brew "gnupg"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Manage compile and link flags for libraries
brew "pkg-config"
# OpenType text shaping engine
brew "harfbuzz"
# Kubernetes package manager
brew "helm"
# Deploy Kubernetes Helm Charts
brew "helmfile"
# Database of common MIME types
brew "shared-mime-info"
# ISO/IEC 23008-12:2017 HEIF file format decoder and encoder
brew "libheif"
# Interpreted, interactive, object-oriented programming language
brew "python@3.9"
# Tools and libraries to manipulate images in many formats
brew "imagemagick"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Run local Kubernetes cluster in Docker
brew "kind"
# Development kit for the Java programming language
brew "openjdk"
# Statically typed programming language for the JVM
brew "kotlin"
# Kubernetes command-line interface
brew "kubernetes-cli"
# Tool that can switch between kubectl contexts easily and create aliases
brew "kubectx"
# Template-free customization of Kubernetes YAML manifests
brew "kustomize"
# Graphical front-end for GCC's coverage testing tool (gcov)
brew "lcov"
# Bare libuv bindings for lua
brew "luv"
# Mac App Store command-line interface
brew "mas"
# Run a Kubernetes cluster locally
brew "minikube"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Manage multiple Node.js versions
brew "nvm"
# Development kit for the Java programming language
brew "openjdk@11"
# Generate clients, server & docs from an OpenAPI spec (v2, v3)
brew "openapi-generator"
# OpenShift command-line interface tools
brew "openshift-cli"
# Fast, disk space efficient package manager
brew "pnpm"
# Tool for managing OCI containers and pods
brew "podman"
# Protocol buffers (Google's data interchange format)
brew "protobuf"
# Interpreted, interactive, object-oriented programming language
brew "python@3.10"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Safe, concurrent, practical language
brew "rust"
# Command-line tool for the Amazon S3 service
brew "s3cmd"
# Easy and Repeatable Kubernetes Development
brew "skaffold"
# Cleans your SVG files by removing unnecessary data
brew "svgcleaner"
# High-performance system programming language
brew "swift"
# Tool to build, change, and version infrastructure
brew "terraform"
# Linter for Terraform files
brew "tflint"
# Terminal multiplexer
brew "tmux"
# Vi 'workalike' with many additional features
brew "vim"
# Internet file retriever
brew "wget"
# Check your $HOME for unwanted files and directories
brew "xdg-ninja"
# JavaScript package manager
brew "yarn"
# General-purpose lossless data-compression library
brew "zlib"
# UNIX shell (command interpreter)
brew "zsh"
# A command-line tool for The Flutter code generator for your assets, fonts, colors, … — Get rid of all String-based APIs. by Dart.
brew "fluttergen/tap/fluttergen"
# Everything you need to get started with Heroku
brew "heroku/brew/heroku"
# Simple hotkey-daemon for macOS.
brew "koekeishiya/formulae/skhd"
# A tiling window manager for macOS based on binary space partitioning.
brew "koekeishiya/formulae/yabai"
# Simple cli to manage Flutter SDK versions per project
brew "leoafarias/fvm/fvm"
# A CLI tool to build for the Shopify platform
brew "shopify/shopify/shopify-cli"
# Stripe CLI utility
brew "stripe/stripe-cli/stripe"
# Command-line interface for 1Password
cask "1password-cli"
# Collection of apps and services for photography, design, video, web, and UX
cask "adobe-creative-cloud"
# Distribution of the Python and R programming languages for scientific computing
cask "anaconda"
# Command-line tools for building and debugging Android apps
cask "android-commandlinetools"
# Toolset to implement parts of Android apps in native code
cask "android-ndk"
# Android SDK component
cask "android-platform-tools"
# Tools for building Android applications
cask "android-studio"
# Redis desktop manager
cask "another-redis-desktop-manager"
# Web browser focusing on privacy
cask "brave-browser"
# Run Stable Diffusion locally
cask "diffusionbee"
# Voice and text chat software
cask "discord"
# App to build and share containerized applications and microservices
cask "docker"
# Status monitoring
cask "eul"
# Developer targeted fonts with a high number of glyphs
cask "font-hack-nerd-font"
# Desktop client for GitHub repositories
cask "github"
# Web browser
cask "google-chrome"
# HTTP and GraphQL Client
cask "insomnia"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2-beta"
# GPU-based terminal emulator
cask "kitty"
# Screen and video recording software
cask "loom"
# Provides updates to various Microsoft products
cask "microsoft-auto-update"
# Office suite
cask "microsoft-office"
# Meet, chat, call, and collaborate in just one place
cask "microsoft-teams"
# Knowledge base that works on top of a local folder of plain text Markdown files
cask "obsidian"
# Administration and development platform for PostgreSQL
cask "pgadmin4"
# Collaboration platform for API development
cask "postman"
# Kubernetes and container management on the desktop
cask "rancher"
# Data science software focusing on R and Python
cask "rstudio"
# Team communication and collaboration software
cask "slack"
# Music streaming service
cask "spotify"
# JDK from the Eclipse Foundation (Adoptium)
cask "temurin"
# Virtual machines UI using QEMU
cask "utm"
# Open-source code editor
cask "visual-studio-code"
# Native desktop client for WhatsApp
cask "whatsapp"
# Video communication and virtual meeting platform
cask "zoom"
mas "Be Focused", id: 973134470
mas "BetterSnapTool", id: 417375580
mas "DevCleaner", id: 1388020431
mas "Disk Space Pro", id: 636899298
mas "HP Smart", id: 1474276998
mas "Keynote", id: 409183694
mas "Notion Web Clipper", id: 1559269364
mas "TestFlight", id: 899247664
mas "Timery", id: 1425368544
mas "Todoist", id: 585829637
mas "Toggl Track", id: 957734279
mas "Xcode", id: 497799835
vscode "aaron-bond.better-comments"
vscode "albert.TabOut"
vscode "alexisvt.flutter-snippets"
vscode "alexkrechik.cucumberautocomplete"
vscode "asvetliakov.vscode-neovim"
vscode "batisteo.vscode-django"
vscode "BendixMa.dart-data-class-generator"
vscode "berublan.vscode-log-viewer"
vscode "blaugold.melos-code"
vscode "bradlc.vscode-tailwindcss"
vscode "CS50.vscode-presentation-mode"
vscode "csstools.postcss"
vscode "Dart-Code.dart-code"
vscode "Dart-Code.flutter"
vscode "dbaeumer.vscode-eslint"
vscode "donjayamanne.python-environment-manager"
vscode "donjayamanne.python-extension-pack"
vscode "dracula-theme.theme-dracula"
vscode "dsznajder.es7-react-js-snippets"
vscode "eamodio.gitlens"
vscode "ecmel.vscode-html-css"
vscode "edonet.vscode-command-runner"
vscode "emilast.LogFileHighlighter"
vscode "enkia.tokyo-night"
vscode "Equinusocio.vsc-community-material-theme"
vscode "esbenp.prettier-vscode"
vscode "EXCEEDSYSTEM.vscode-macros"
vscode "flutterando.flutter-coverage"
vscode "Flutterbricksproductions.flutterbricks"
vscode "gamunu.vscode-yarn"
vscode "GitHub.codespaces"
vscode "GitHub.copilot"
vscode "GitHub.copilot-chat"
vscode "GitHub.copilot-labs"
vscode "github.vscode-github-actions"
vscode "GitHub.vscode-pull-request-github"
vscode "Google.arb-editor"
vscode "GrapeCity.gc-excelviewer"
vscode "Gruntfuggly.todo-tree"
vscode "Gruntfuggly.triggertaskonsave"
vscode "hashicorp.terraform"
vscode "humao.rest-client"
vscode "jeff-hykin.better-cpp-syntax"
vscode "johnstew.gif"
vscode "jspolancor.presentationmode"
vscode "KevinRose.vsc-python-indent"
vscode "LeetCode.vscode-leetcode"
vscode "localizely.flutter-intl"
vscode "luanpotter.dart-import"
vscode "lunuan.kubernetes-templates"
vscode "mathiasfrohlich.Kotlin"
vscode "monokai.theme-monokai-pro-vscode"
vscode "ms-azuretools.vscode-docker"
vscode "ms-dotnettools.vscode-dotnet-runtime"
vscode "ms-kubernetes-tools.vscode-kubernetes-tools"
vscode "ms-python.black-formatter"
vscode "ms-python.isort"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode-remote.remote-wsl"
vscode "ms-vscode-remote.vscode-remote-extensionpack"
vscode "ms-vscode.js-debug-nightly"
vscode "ms-vscode.remote-explorer"
vscode "ms-vscode.remote-server"
vscode "ms-vsliveshare.vsliveshare"
vscode "ms-vsliveshare.vsliveshare-pack"
vscode "mutantdino.resourcemonitor"
vscode "Nash.awesome-flutter-snippets"
vscode "nicollasr.vscode-streamdeck"
vscode "njpwerner.autodocstring"
vscode "orestesgaolin.dart-export-index"
vscode "oscarcs.dart-syntax-highlighting-only"
vscode "patbenatar.advanced-new-file"
vscode "paulshen.paul-typescript-toolkit"
vscode "PeterSchmalfeldt.explorer-exclude"
vscode "pflannery.vscode-versionlens"
vscode "PKief.material-icon-theme"
vscode "plibither8.remove-comments"
vscode "Prisma.prisma"
vscode "redhat.java"
vscode "redhat.vscode-commons"
vscode "redhat.vscode-xml"
vscode "redhat.vscode-yaml"
vscode "RobbOwen.synthwave-vscode"
vscode "robert-brunhage.flutter-riverpod-snippets"
vscode "rust-lang.rust-analyzer"
vscode "rvest.vs-code-prettier-eslint"
vscode "SergeLamikhov.lcov-lang"
vscode "sswg.swift-lang"
vscode "streetsidesoftware.code-spell-checker"
vscode "SupernovaIO.pulsar-vsc-extension"
vscode "tamasfe.even-better-toml"
vscode "tumido.crd-snippets"
vscode "unifiedjs.vscode-mdx"
vscode "usernamehw.errorlens"
vscode "vadimcn.vscode-lldb"
vscode "VisualStudioExptTeam.intellicode-api-usage-examples"
vscode "VisualStudioExptTeam.vscodeintellicode"
vscode "vscjava.vscode-gradle"
vscode "vscjava.vscode-java-debug"
vscode "vscjava.vscode-java-dependency"
vscode "vscjava.vscode-java-pack"
vscode "vscjava.vscode-java-test"
vscode "vscjava.vscode-maven"
vscode "vscode-ext.sync-rsync"
vscode "vscode-icons-team.vscode-icons"
vscode "vscodevim.vim"
vscode "wholroyd.jinja"
vscode "wix.glean"
vscode "Wscats.cors-browser"
vscode "xaver.clang-format"
vscode "yaamaa.disable-mouse"
vscode "Zarifprogrammer.tailwind-snippets"
vscode "zhuangtongfa.material-theme"
vscode "zxh404.vscode-proto3"
