#!/usr/bin/env bash

set -e

PROFILE=$1
BREWFILE="${PROFILE:+$PROFILE/}Brewfile"
CONFIG="install${PROFILE:+.$PROFILE}.conf.yaml"

if [ -z "$PROFILE" ]; then
    echo "No profile specified, using default"
else
    shift # remove the first argument
fi

DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"

