nerdfont: true

agent: claude
merge_strategy: rebase
mode: session

worktree_naming: basename # full | basename
# worktree_dir: "{project}-wt"

# panes:
#   - command: <agent>
#     focus: true
windows:
  # - name: <project>--<worktree>
  - panes:
      - command: <agent>
        focus: true
  - panes:
      - command: pnpm install && pnpm run env:pull
        focus: false

# post_create:
#   - pnpm install
#   - pnpm run env:pull
