os:
  open: 'test -n "$NVIM" && nvim --server "$NVIM" --remote "{{filename}}" || open "{{filename}}"'
git:
  pagers:
    - colorArg: always
      pager: delta --dark --side-by-side --paging=never --line-numbers
