model = "gpt-5.5"
model_reasoning_effort = "high"
personality = "pragmatic"
sandbox_mode = "workspace-write"
approval_policy = "on-request"

notify = ["/Users/pattobrien/.codex/computer-use/Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient", "turn-ended"]

[projects."/Users/pattobrien/dev/getdots/meagain-bare"]
trust_level = "trusted"

[projects."/Users/pattobrien/dev/exploring/tellescope"]
trust_level = "trusted"

[projects."/Users/pattobrien/dev/gd/meagain"]
trust_level = "trusted"

[projects."/Users/pattobrien"]
trust_level = "trusted"

[projects."/Users/pattobrien/.dotfiles"]
trust_level = "trusted"

[notice.model_migrations]
"gpt-5.3-codex" = "gpt-5.4"

[features]
hooks = true
multi_agent = true

[marketplaces.openai-bundled]
last_updated = "2026-05-14T02:36:28Z"
source_type = "local"
source = "/Users/pattobrien/.codex/.tmp/bundled-marketplaces/openai-bundled"

[marketplaces.openai-primary-runtime]
last_updated = "2026-05-14T03:23:12Z"
source_type = "local"
source = "/Users/pattobrien/.cache/codex-runtimes/codex-primary-runtime/plugins/openai-primary-runtime"

[plugins."computer-use@openai-bundled"]
enabled = true

[plugins."github@openai-curated"]
enabled = true

[plugins."browser-use@openai-bundled"]
enabled = true

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[tui.keymap.editor]
insert_newline = "shift-enter"

[tui.model_availability_nux]
"gpt-5.5" = 4
