#!/usr/bin/env bash
set -euo pipefail

echo "Updating asdf plugins..."
asdf plugin update --all

echo "Dumping Brewfile..."
~/dev/pattobrien/dotfiles/scripts/brew-dump-leaves ~/dev/pattobrien/dotfiles/brew/personal/Brewfile

echo "Cleaning up..."
brew cleanup --prune=30 -s

echo "Done!"
