
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export ZSH="$HOME/.oh-my-zsh" # Path to your oh-my-zsh installation.


if [ "$TERM_PROGRAM" != "vscode" ] || [ "$COLORTERM" != "truecolor" ]; then
      export TERM=xterm-kitty
fi

[[ -n $TMUX ]] && export TERM="xterm-256color"

ZSH_THEME="powerlevel10k/powerlevel10k"

# Below are miscellaneous OH MY ZSH settings that could be useful
# CASE_SENSITIVE="true" # case-sensitive completion.
# ENABLE_CORRECTION="true" # command auto-correction.
# DISABLE_UNTRACKED_FILES_DIRTY="true"
# ZSH_CUSTOM=/path/to/new-custom-folder # use another custom folder than $ZSH/custom?

# Custom plugins may be added to $ZSH_CUSTOM/plugins/, such as rails git textmate ruby lighthouse
plugins=(git zsh-autosuggestions zsh-syntax-highlighting web-search)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Set personal aliases, overriding those provided by oh-my-zsh
# For a full list of active aliases, run `alias`.
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh


export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

eval $(/opt/homebrew/bin/brew shellenv)

export PATH="/usr/local/opt/ruby/bin:$PATH"
export GEM_HOME="$HOME/.gem" 

export NVM_DIR="${HOME}/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

## add tmux-sessionizer
PATH=$PATH:~/.local/bin

source ~/.dotfiles/zsh/python.zsh
source ~/.dotfiles/zsh/credentials.zsh
source ~/.dotfiles/zsh/flutter.zsh
## [Completion] 
## Completion scripts setup. Remove the following line to uninstall
[[ -f /Users/pattobrien/.dart-cli-completion/zsh-config.zsh ]] && . /Users/pattobrien/.dart-cli-completion/zsh-config.zsh || true
## [/Completion]

