#!/bin/zsh

# initialize tmux if it's not already running in the current shell
# NOTE: this must be initialized before p10k is initialized
if [ "$TERM_PROGRAM" != "vscode" ] && [ -z "$TMUX" ]; then
  exec tmux new-session -A -s workspace
fi


# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export ZSH="$HOME/.oh-my-zsh" # Path to your oh-my-zsh installation.

# if [ "$TERM_PROGRAM" != "vscode" ] || [ "$COLORTERM" != "truecolor" ]; then
#       export TERM=xterm-kitty
# fi

# sets the TERM var if $TMUX is set and not empty
[[ -n $TMUX ]] && export TERM="xterm-256color"

ZSH_THEME="powerlevel10k/powerlevel10k"

# Below are miscellaneous OH MY ZSH settings that could be useful
# CASE_SENSITIVE="true" # case-sensitive completion.
# ENABLE_CORRECTION="true" # command auto-correction.
# DISABLE_UNTRACKED_FILES_DIRTY="true"
# ZSH_CUSTOM=/path/to/new-custom-folder # use another custom folder than $ZSH/custom?

# Custom plugins may be added to $ZSH_CUSTOM/plugins/
plugins=(
  git 
  zsh-autosuggestions 
  zsh-syntax-highlighting 
  zsh-interactive-cd

  # untested plugins below:
  web-search
  1password
  gh
  keychain
  kubectl
  minikube
  kind
  skaffold # autocompletion
  terraform # aliases and autocompletion
  # doctl # this causes 1password prompt when re-sourcing zshrc file, for some reason... so we should not use this

  # other plugins available that we should install at some point:
  # vi-mode
  # nvm
  # npm
  # macos
  # tmux
  # tmuxinator (?)
  # vscode
  # dotenv - source .env variables when you cd into a directory
  # aliases - lists the shortcuts currently available
  # common-aliases
  # flutter - aliases for flutter commands
  # fzf
  # gcloud
  # git-auto-fetch
  # github
  # gitignore
  # git-lfs
  # helm
  # kubectx
  # mongocli
  # operator-sdk
  # pod - cocoaPods completion
  # redis-cli
  # salt
  # ssh-agent - configure ssh-agent settings
  # web-search
  # xcode
)

# enable zsh completions from homebrew (note: must be done before oh-my-zsh.sh is sourced)
PATH="$(brew --prefix)/share/zsh/site-functions:${PATH}"

source $ZSH/oh-my-zsh.sh  


# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Set personal aliases, overriding those provided by oh-my-zsh
# For a full list of active aliases, run `alias`.
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh  

export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

eval $(/opt/homebrew/bin/brew shellenv)

# MISC PATHS
export PATH="/usr/local/opt/ruby/bin:$PATH"
export GEM_HOME="$HOME/.gem" 
export KUBE_CONFIG_PATH="$HOME/.kube/config"


export NVM_DIR="$HOME/.nvm"
# TODO: The following line causes the terminal to have latency issues
# [ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

## add tmux-sessionizer
bindkey -s ^f "tmux-sessionizer\n"
PATH=$PATH:~/.local/bin


source ~/.dotfiles/zsh/python.zsh
source ~/.dotfiles/zsh/credentials.zsh
source ~/.dotfiles/zsh/flutter.zsh
source ~/.dotfiles/zsh/aliases.zsh
# [Completion] 
# Completion scripts setup. Remove the following line to uninstall
[[ -f /Users/pattobrien/.dart-cli-completion/zsh-config.zsh ]] && . /Users/pattobrien/.dart-cli-completion/zsh-config.zsh || true
# [/Completion]

# source <(kubectl completion zsh)
# source <(k completion zsh)
# source <(helm completion zsh)
# source <(helmfile completion zsh)
## source <(kubectx completion zsh)

# # set up vim motions in zsh
bindkey -v 
# tabtab source for packages
# uninstall by removing these lines
# [[ -f ~/.config/tabtab/zsh/__tabtab.zsh ]] && . ~/.config/tabtab/zsh/__tabtab.zsh || true

# pnpm
export PNPM_HOME="/Users/pattobrien/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac

### MANAGED BY RANCHER DESKTOP START (DO NOT EDIT)
export PATH="/Users/pattobrien/.rd/bin:$PATH"
### MANAGED BY RANCHER DESKTOP END (DO NOT EDIT)

alias exa='exa -laFh --git --icons'
alias ls='exa'
